exports.terms= [
  "Fluor NOT NOT NYSE"
]

exports.terms1 = [
"483 observation letter",
  "Respules",
  "Albuterol",
  "FDA warning",
  "Sandoz",
  "Viatris",
  "Aurobindo",
  "Sun Pharma",
  "Doc. Reddy’s Laboratories",
  "impeachment inquiry",
  "Biden impeachment",
  "Mayorkas impeachment",
  "Keisha Lance Bottoms",
  " Georgia Raise",
  " student loan debt forgiveness",
  " Georgia Peanut Gallery",
  " Voices for a Healthy Georgia",
  "Tanya McLean",
  "Leaders of Kenosha",
  "Raising Wisconsin",
  "Wisconsin Early Childhood Association",
  "Megan Wolfe",
  "Redistricting",
  "redistricting lawsuit",
  "parental leave",
  "postpartum",
  "gerrymandering",
  "maternal health",
  "Tony Evers",
  "Governor Evers",
  "Justice David T. Prosser",
  "Wisconsin Supreme Court",
  "Wisconsin State Legislature",
  "Frank Mrvan",
  "Jennifer-Ruth Green",
  "Lisa Grafstein",
  "Tricia Cotham",
  "Tricia Ann Cotham",
  "Patricia Ann Cotham",
  "Patricia Cotham",
  "Yolanda Holmes",
  "Nicole Sidman",
  "Jessica Fitzwater NOT Daybook",
  "Brittany Pettersen",
  "Ron Tupa",
  "Teresa Leger Fernandez",
  "Sharon Clahchischilliage",
  "Sharon E. Clahchischilliage",
  "Jan Gardner",
  "Mariela Roca",
  "Laurie-Anne Sayles",
  "April McClain Delaney",
  "April M. Delaney",
  "April Delaney",
  "April McLain Delaney",
  "Felicia Hopson",
  "Tom Pullion",
  "Allison Eckel",
  "Joanne Schwartz",
  "Deb Buzby-Cope",
  "Alfonso Gambone",
  "Larry Vernamonti",
  "Chris Pritt",
  "Doug Skaff",
  "Natalie Tenant",
  "Terence Everitt",
  "Ashlee Bryan Adams",
  "Woodson Bradley",
  "Nick LaLota",
  "Jim Gaughran",
  "James Gaughran",
  "Craig Herskowitz",
  "Angela Alsobrooks NOT Daybook",
  "Zeke Cohen",
  "Nick Mosby",
  "Shannon C. Sneed",
  "Lisa Stone Barnes",
  "Kandie Smith",
  "Denny Hoskins",
  "Caleb Rowden",
  "Shane Schoeller",
  "Adam Schwadron",
  "Valentina Gomez Noriega",
  "Bobby Hanig",
  "Val Applewhite",
  "Jay Chaudhuri",
  "Jaime Daniell",
  "Christine Weason",
  "Alexander Paschall",
  "Andrei Cherny",
  "Marlene Galan Woods",
  "LGBTQ Victory Fund",
  " Human Rights Campaign",
  " Stonewall Democrats",
  " LGBTQ voters",
  " LGBTQ+ policy",
  " LGBTQ rights",
  " trans kids",
  " trans rights",
  " bathroom bill",
  "Gavin Newsom",
  "Eleni Kounalakis",
  "Karen Bass",
  "Alex Padilla",
  "Laphonza Butler",
  "cost of living",
  "California voters",
  "ballot measure",
  "ballot initiative",
  "referendum",
  "healthcare",
  "health care",
  "Pomona United for Stable Housing",
  "Costa-Hawkins",
  "Costa Hawkins",
  "affordable housing",
  "tenants rights",
  "rent control",
  "340B Program",
  "AT&T",
  "John T. Stankey",
  "John T. Stankey announced",
  "AT&T merger",
  "AT&T Inc.",
  "American Gaming Association",
  "Tommy Barras",
  "The Reynolds Company",
  "David Constable",
  "Fluor NOT NYSE",
  "John W. Ketchum",
  "NextEra NOT NYSE",
  "Smart Heart Sports Coalition",
  "Tom Kuhn NOT Troy",
  "Edison Electric Institute",
  "Christopher C Womack",
  "Southern Company",
  "Univision",
  "David Zumwalt",
  "WISPA",
  " Wireless Internet Service Providers",
  "Emma Walmsley",
  "GlaxoSmithKline",
  " GSK",
  "Ross DeVol",
  "Heartland Forward",
  "Gary Mendell",
  "Rick Cardenas",
  "Rick Cardenas announced",
  "Darden Restaurants",
  "AshBritt",
  "Wayne Peacock",
  "USAA",
  "Evan Marwell",
  "EducationSuperHighway",
  "H Lynn Moore Jr",
  "Tyler Technologies NOT NYSE",
  "Gail Koziara Boudreaux",
  "Elevance Health NOT stock",
  "QCells",
  "Paul Keary",
  "Teneo",
  "Justin Bakes",
  "Forward Financing",
  "Larry Ellison announced",
  "Oracle NOT Oracle Park",
  "Ed Bastian",
  "Ed Bastian announced",
  "Delta Airlines",
  "Damon T. Hininger",
  "Damon Hininger announced",
  "CoreCivic NOT NYSE",
  "Stephen J. Ubl",
  "PhRMA",
  "Bob Sternfels",
  "McKinsey",
  "Alzheimer's Association",
  "Rosalind Brewer",
  "Rosalind Brewer announced",
  "Joseph M. Wassel",
  "FirstNet",
  "Paula Kerger",
  "America’s Public Television Stations",
  "Paula Kerger announced",
  "David A. Ricks",
  "Eli Lilly NOT stock",
  "Kentucky House Democrats",
  "Kentucky Senate Democrats",
  "J. McCauley Brown",
  "James Comer",
  "Sean Southard",
  "Rand Paul",
  "Mitch McConnell",
  "Kentucky Republican Party",
  "Kentucky GOP",
  "Eden Alam",
  " Carol Browner",
  " Mustafa Ali",
  " Sweta Chakraborty"
]